- name: Defining VM(s)
  become: true
  virt:
    name: "{{ item['name'] }}"
    command: "define"
    xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
  with_items: '{{ kvm_vms }}'

- name: config_vms | Creating VM Disk(s)
  become: true
  qemu_img:
    dest: "{{ kvm_images_path }}/{{ item[1]['name'] }}.{{ kvm_images_format_type }}"
    size: "{{ item[1]['size'] }}"
    format: "{{ kvm_images_format_type }}"
  with_subelements:
    - '{{ kvm_vms }}'
    - disks

- name: config_vms | Setting VM State
  become: true
  virt:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] }}"
    with_items: '{{ kvm_vms }}'

- name: config_vms | Setting autostart status
  become: true
  virt:
    name: "{{ item['name'] }}"
    autostart: "{{ item['autostart']|default(omit) }}"
    command: "info"
    with_items: '{{ kvm_vms }}'