- name: config_kvm | Capturing Libvirt Group
  shell: "getent group libvirt | cut -d: -f1"
  register: "_libvirt_group_found"
  changed_when: false
  check_mode: no

- name: config_kvm | Capturing Libvirt Group
  shell: "getent group libvirtd | cut -d: -f1"
  register: "_libvirtd_group_found"
  changed_when: false
  check_mode: no

- name: config_kvm | Setting unix_sock_group
  set_fact:
    kvm_unix_sock_group: 'libvirt'
  when: >
        (_libvirt_group_found is defined and
          _libvirt_group_found['stdout'] == 'libvirt')
- name: config_kvm | Setting unix_sock_group
  set_fact:
    kvm_unix_sock_group: 'libvirtd'
  when: >
        (_libvirtd_group_found is defined and
          _libvirtd_group_found['stdout'] == 'libvirtd')