- include_tasks: hw_virtualization_check.yml

- name: Installing KVM
  become: true
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - bridge-utils
    - libvirt-bin
    - lldpd
    - python-libvirt
    - python-lxml
    - qemu-kvm

- include_tasks: get_group.yml
- include_tasks: users.yml
- include_tasks: sysctl.yml

- include_tasks: create_vms.yml