---
- hosts: k8s-cluster:children
  roles:
    - precheck

- import_playbook: kubespray/cluster.yml

- hosts: kube-master[0]
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - cassandra
    - prometheus