- name: Create VM dirs
  become: yes
  file:
    path: "{{ vms_dir }}"
    state: directory
    mode: 0777

- name: Copy Vagrantfile
  template:
    src: "{{ item }}.j2"
    dest: ./{{ item }}
  with_items:
    - Vagrantfile
  delegate_to: localhost





