- name: Create VM dirs
  become: yes
  file:
    path: /vagrant
    state: directory

- name: Copy Vagrantfile
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /vagrant/{{ item }}
  with_items:
    - Vagrantfile

#- name: Vagrant Up
#  become: yes
#  command: vagrant init up
#    agrs:
#      chdir: /vagrant



