- name: Create VM dirs
  file:
    path: ../vagrant
    state: directory
  delegate_to: localhost

- name: Copy Vagrantfile
  template:
    src: "{{ item }}.j2"
    dest: ../vagrant/{{ item }}
  with_items:
    - Vagrantfile
  delegate_to: localhost

#- name: Vagrant Up
#  command: vagrant up
#    agrs:
#      chdir: ../vagrant
#  delegate_to: localhost



