- name: Create VM dirs
  become: yes
  file:
    path: "{{ vms_dir }}"
    state: directory
    mode: 0777

- name: Copy Vagrantfile
  template:
    src: "{{ item }}.j2"
    dest: "{{ vms_dir }}/{{ item }}"
  with_items:
    - Vagrantfile

- name: Vagrant Up
  command: vagrant up
    agrs:
      chdir: ../vagrant




