- name: Create deb dir
  become: yes
  file:
    path: "{{ vagrant_debdir }}"
    state: directory

- name: Download vagrant
  become: yes
  get_url:
    url: https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb
    dest: "{{ vagrant_debdir }}"

- name: Install vagrant
  become: yes
  apt:
    deb: "{{ vagrant_debdir }}/vagrant_2.0.2_x86_64.deb"

- name: Add mappings to /etc/hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['kube-master'] %}
      {{ hostvars[host]['ip'] }} {{ host }}
      {% endif %}
      {% for host in groups['kube-node'] %}
      {{ hostvars[host]['ip'] }} {{ host }}
      {% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- include_tasks: create_vm.yml