- name: Copy cassandra configs
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /tmp/{{ item }}
  with_items:
    - cassandra-service.yaml
    - cassandra-statefulset.yaml
  when: inventory_hostname == groups['kube-master'][0]

- name: Create cassandra service
  become: yes
  kube:
    name: "cassandra"
    namespace: "default"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "Service"
    filename: "/tmp/cassandra-service.yaml"
    state: "latest"
  when: inventory_hostname == groups['kube-master'][0]

- name: Start cassandra
  become: yes
  kube:
    name: "cassandra"
    namespace: "default"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "StatefulSet"
    filename: "/tmp/cassandra-statefulset.yaml"
    state: "latest"
  when: inventory_hostname == groups['kube-master'][0]