- name: Copy cassandra configs
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "{{ kube_config_dir }}/{{ item }}"
  with_items:
    - cassandra-service.yaml
    - cassandra-service-metrics.yaml
    - cassandra-statefulset.yaml
  when: inventory_hostname == groups['kube-master'][0]

- name: Start cassandra
  become: yes
  kube:
    name: "cassandra"
    namespace: "default"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "{{ item.resource }}"
    filename: "{{ kube_config_dir }}/{{ item.config }}"
    state: "latest"
  with_items:
    - { config: cassandra-service.yaml, resource: Service }
    - { config: cassandra-statefulset.yaml, resource: StatefulSet }
    - { config: cassandra-service-metrics.yaml, resource: Service }
  when: inventory_hostname == groups['kube-master'][0]
