- name: add apt-key
  become: yes
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: add virtualbox repo
  become: yes
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: yes

- name: install virtualbox
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dkms
    - virtualbox-5.1
  become: yes
