- name: Install for Debian
  include_tasks: "debian.yml"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install for CentOS
  include_tasks: "centos.yml"
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
